import numpy as np

NUM_ROWS = 101
NUM_COLS = 101
INF = 1e9

X = [1, 0, -1, 0]
Y = [0, 1, 0, -1]

STARTING_POSITION_OF_AGENT = (0, 0)
GOAL_POSITION_OF_AGENT = (NUM_ROWS-1, NUM_COLS-1)

NUM_ITERATION_FOR_EACH_PROBABILITY = 10
NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY = 11
START_PROBABILITY = 0.0
END_PROBABILITY = 0.33

LIST_OF_PROBABILITIES = np.linspace(START_PROBABILITY, END_PROBABILITY, NUM_UNIFORM_SAMPLE_FOR_EACH_PROBABILITY)